version: '3'
services:
  XmlFeedPrc:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    image: python:3.10-slim-add-install_jma-xml-apsv
    container_name: jma-xml-XmlFeedPrc
    hostname: jma-xml-XmlFeedPrc
    volumes:
      - ./src:/app
    depends_on:
      - mongo
    command: /bin/sh -c "python3 XmlFeedPrc.py"

  DownLoader:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    image: python:3.10-slim-add-install_jma-xml-apsv
    container_name: jma-xml-DownLoader
    hostname: jma-xml-DownLoader
    volumes:
      - ./src:/app
    depends_on:
      - mongo
    command: /bin/sh -c "python3 DownLoader.py"

  mongo:
    image: mongo
    container_name: jma-xml-mongo
    hostname: jma-xml-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb_data:/data/db
      - ./configdb:/data/configdb
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    container_name: jma-xml-mongo_express
    ports:
      - 15000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: jma-xml-mongo
    depends_on:
      mongo:
        condition: service_healthy
